const API=localStorage.getItem('nexgene_api')||'http://localhost:8000';let token=localStorage.getItem('nexgene_token')||'',mode='',idx=0,data={};
const M=[['sleep_duration','How long did you sleep?','Pick the window that feels closest.',[['◔','Under 5h',4.5],['◑','5–6h',5.5],['◒','6–7h',6.5],['◕','7–8h',7.5],['●','8h+',8.5]]],['sleep_quality','How restorative was it?','Quality matters as much as duration.',[['1','Poor',1],['2','Fair',2],['3','Okay',3],['4','Good',4],['5','Great',5]]],['energy','Energy right now','Tap the level that matches your body.',[['1','Drained',1],['2','Low',2],['3','Steady',3],['4','Strong',4],['5','High',5]]]];
const E=[['mood','Mood overall','No need to overthink it.',[['1','Low',1],['2','Soft',2],['3','Neutral',3],['4','Good',4],['5','Bright',5]]],['stress','Stress level','What is the pressure like today?',[['1','Calm',1],['2','Mild',2],['3','Medium',3],['4','High',4],['5','Heavy',5]]],['focus','Focus / clarity','How clear did your mind feel?',[['1','Foggy',1],['2','Scattered',2],['3','Okay',3],['4','Clear',4],['5','Sharp',5]]],['activity_level','Movement today','Anything from a walk to a hard session counts.',[['1','None',1],['2','Light',2],['3','Moderate',3],['4','Active',4],['5','Intense',5]]],['diet_quality','How you ate','Rough sense of nourishment, not perfection.',[['1','Off',1],['2','Mixed',2],['3','Okay',3],['4','Solid',4],['5','Great',5]]],['nicotine','Nicotine today','Optional signal. Be honest with yourself.',[['0','None',0],['1','Light',1],['2','Some',2],['3','More',3],['4','Heavy',4]]],['alcohol','Alcohol today','Optional lifestyle context.',[['0','None',0],['1','Light',1],['2','Some',2],['3','More',3],['4','Heavy',4]]],['caffeine','Caffeine today','Coffee, tea, energy drinks, etc.',[['0','None',0],['1','Light',1],['2','Some',2],['3','More',3],['4','Heavy',4]]]];
function h(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]));}
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}}if(!r.ok)throw new Error(j.detail||j.message||r.statusText);return j;}
function account(){document.getElementById('auth').classList.toggle('hide');}
async function register(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;try{const r=await api('/api/v1/auth/register',{method:'POST',body:JSON.stringify({email,password})});token=r.access_token;localStorage.setItem('nexgene_token',token);document.getElementById('auth').classList.add('hide');document.getElementById('account').textContent='SIGNED IN';loadAll();}catch(e){document.getElementById('authmsg').textContent=e.message;}}
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;try{const r=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})});token=r.access_token;localStorage.setItem('nexgene_token',token);document.getElementById('auth').classList.add('hide');document.getElementById('account').textContent='SIGNED IN';loadAll();}catch(e){document.getElementById('authmsg').textContent=e.message;}}
function showView(v){['today','patterns','timeline'].forEach(x=>{document.getElementById(x+'View').classList.toggle('hide',x!==v);document.getElementById('n'+x[0].toUpperCase()+x.slice(1)).classList.toggle('active',x===v);});if(v==='patterns')loadPatterns();if(v==='timeline')loadTimeline();}
function start(m){if(!token){account();return;}mode=m;idx=0;data={};document.getElementById('sheet').classList.remove('hide');renderStep();}
function closeSheet(){document.getElementById('sheet').classList.add('hide');}
function renderStep(){const steps=mode==='morning'?M:E;const s=steps[idx];document.getElementById('step').textContent=`${idx+1} / ${steps.length}`;document.getElementById('q').innerHTML=`<h3>${h(s[1])}</h3><p>${h(s[2])}</p>`;document.getElementById('choices').innerHTML=s[3].map(([icon,label,val])=>`<button class="choice" data-v="${val}" onclick="pick(this,${val})">${icon}<span>${h(label)}</span></button>`).join('');document.getElementById('next').disabled=true;}
function pick(el,val){document.querySelectorAll('.choice').forEach(b=>b.classList.remove('on'));el.classList.add('on');const steps=mode==='morning'?M:E;data[steps[idx][0]]=val;document.getElementById('next').disabled=false;}
async function nextStep(){const steps=mode==='morning'?M:E;if(idx<steps.length-1){idx++;renderStep();return;}try{await api(`/api/v1/checkins/${mode}`,{method:'POST',body:JSON.stringify({values:data})});closeSheet();loadAll();}catch(e){alert(e.message);}}
async function loadAll(){if(!token)return;try{const t=await api('/api/v1/today');const keys=Object.keys(t);document.getElementById('count').textContent=`${Math.min(2,Math.ceil(keys.length/3))} / 2 check-ins`;document.getElementById('bar').style.width=`${Math.min(100,keys.length*12)}%`;const snap=document.getElementById('snapshot');if(!keys.length)snap.innerHTML='<div class="empty"><b>A quiet page.</b><span>Two tiny check-ins begin the picture.</span></div>';else snap.innerHTML=keys.slice(0,8).map(k=>`<div class="card"><b>${h(String(t[k]))}</b><span>${h(k.replace(/_/g,' '))}</span></div>`).join('');const ins=await api('/api/v1/insights');document.getElementById('insight').textContent=(ins.items&&ins.items[0])||'Your baseline is beginning to take shape.';}catch(e){console.warn(e);}}
async function loadPatterns(){if(!token)return;try{const p=await api('/api/v1/patterns?days=30');const cards=document.getElementById('patternCards');const av=p.averages||{};cards.innerHTML=Object.entries(av).map(([k,v])=>`<div class="pcard"><b>${v}</b><span>${h(k.replace(/_/g,' '))}</span></div>`).join('')||'<div class="empty">Not enough data yet.</div>';const chart=document.getElementById('chart');const series=p.series||[];if(!series.length){chart.innerHTML='<div class="empty">Charts appear after a few check-ins.</div>';return;}const max=Math.max(...series.flatMap(d=>[d.sleep_duration||0,d.focus||0]),1);chart.innerHTML=series.slice(-14).map(d=>{const s=((d.sleep_duration||0)/max)*100,f=((d.focus||0)/max)*100;return `<div class="barcol" title="${h(d.date)}"><i style="height:${s}%"></i><i class="f" style="height:${f}%"></i></div>`;}).join('');}catch(e){console.warn(e);}}
async function loadTimeline(){if(!token)return;try{const rows=await api('/api/v1/timeline');const el=document.getElementById('timeline');if(!rows.length){el.innerHTML='<div class="empty">Your timeline is empty.</div>';return;}el.innerHTML=rows.slice(0,40).map(r=>`<div class="titem"><b>${h(String(r.value))}</b><span>${h(r.kind.replace(/_/g,' '))}</span><small>${h(r.recorded_at.slice(0,16).replace('T',' '))}</small></div>`).join('');}catch(e){console.warn(e);}}
(function init(){const h=new Date().getHours();document.getElementById('greeting').textContent=h<12?'Good morning.':h<18?'Good afternoon.':'Good evening.';document.getElementById('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase();if(token){document.getElementById('account').textContent='SIGNED IN';loadAll();}})();
