const API=window.location.origin.replace(/\/$/,'');let csrf='',mode='',idx=0,data={};
const M=[['sleep_duration','How long did you sleep?','Pick the window that feels closest.',[['◔','Under 5h',4.5],['◑','5–6h',5.5],['◒','6–7h',6.5],['◕','7–8h',7.5],['◉','8–9h',8.5],['✦','9h+',9.5]]],['sleep_quality','How did your sleep feel?','No scorekeeping. Just your read.',[['☹','Rough',2],['◔','Restless',4],['◑','Okay',6],['◕','Good',8],['☺','Deep',10]]],['energy','How are you arriving today?','First instinct.',[['🪫','Drained',2],['◔','Low',4],['◑','Steady',6],['◕','Good',8],['⚡','Charged',10]]],['morning_context','Anything unusual?','Optional. You can always skip.',[['○','Nothing unusual','none'],['◌','Headache','headache'],['⌁','Fatigue','fatigue'],['△','Pain','pain'],['→','Skip','skipped']]]];
const E=[['mood','How was today?','The overall texture of the day.',[['☹','Low',2],['◔','Heavy',4],['◑','Mixed',6],['◕','Good',8],['☺','Great',10]]],['stress','Where was your stress?','Today’s signal, not a diagnosis.',[['○','Very low',1],['◔','Low',3],['◑','Moderate',5],['◕','High',7],['●','Very high',9]]],['focus','How was your focus?','How easy was it to stay with things?',[['☁','Scattered',2],['◔','Patchy',4],['◑','Okay',6],['◕','Strong',8],['◎','Locked in',10]]],['activity_level','How much did you move?','Minutes can come later.',[['○','Very little','very_little'],['◔','Light','light'],['◑','Moderate','moderate'],['◕','A lot','high'],['→','Skip','skipped']]],['diet_quality','How did you eat?','Think balance, not calories.',[['·','Chaotic','low'],['◔','Mostly quick','fair'],['◑','Mixed','mixed'],['◕','Mostly balanced','good'],['✦','Very balanced','high']]],['caffeine','Caffeine today?','Coffee, tea and energy drinks count.',[['○','None',0],['◔','1','1'],['◑','2','2'],['◕','3+','3']]],['alcohol','Alcohol today?','Optional, no judgement.',[['○','None',0],['◔','1','1'],['◑','2','2'],['◕','3+','3']]],['nicotine','Nicotine / smoking?','Optional context for your baseline.',[['○','None','none'],['◔','Some','some'],['◕','Frequent','frequent']]]];
const $=id=>document.getElementById(id);async function account(){if(csrf){await fetch(API+'/api/v1/auth/logout',{method:'POST',headers:{'X-CSRF-Token':csrf}});csrf='';$('account').textContent='SIGN IN';alert('Signed out.');}else $('auth').classList.toggle('hide')}
async function authCall(path){const email=$('email').value.trim().toLowerCase(),password=$('password').value;if(!email||password.length<12||!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password)||!/[^A-Za-z0-9]/.test(password)){$('authmsg').textContent='Use 12+ chars with upper, lower, number, symbol.';return}$('authmsg').textContent='Working…';try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Auth failed');csrf=document.cookie.split('; ').find(x=>x.startsWith('nexgene_csrf='))?.split('=')[1]||'';$('auth').classList.add('hide');$('account').textContent='SIGN OUT';$('authmsg').textContent='';await load()}catch(e){$('authmsg').textContent=e.message}}
function register(){authCall('/api/v1/auth/register')}function login(){authCall('/api/v1/auth/login')}
async function get(path){const r=await fetch(API+path,{credentials:'include'});if(r.status===401){csrf='';$('account').textContent='SIGN IN';return{}}return r.json()}
function start(m){if(!csrf){$('auth').classList.remove('hide');$('authmsg').textContent='Create an account first. Your check-ins need somewhere private to live.';return}mode=m;idx=0;data={};$('sheet').classList.remove('hide');render()}
function render(){const arr=mode==='morning'?M:E,item=arr[idx];$('step').textContent=`${idx+1} / ${arr.length}`;$('q').innerHTML=`<div class="k">${mode} check-in</div><h3>${item[1]}</h3><p>${item[2]}</p>`;$('choices').innerHTML='';item[3].forEach(o=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<i>${o[0]}</i><b>${o[1]}</b>`;b.onclick=()=>{[...$('choices').children].forEach(x=>x.classList.remove('sel'));b.classList.add('sel');data[item[0]]=o[2];$('next').disabled=false};$('choices').appendChild(b)});$('next').disabled=true}
function closeSheet(){$('sheet').classList.add('hide')}
async function nextStep(){const arr=mode==='morning'?M:E;if(idx<arr.length-1){idx++;render();return}$('next').disabled=true;$('next').textContent='Saving…';try{await fetch(API+'/api/v1/checkins/'+mode,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},credentials:'include',body:JSON.stringify({values:data})});closeSheet();$('next').textContent='CONTINUE';await load()}catch(e){alert(e.message||'Save failed');$('next').textContent='CONTINUE';$('next').disabled=false}}
function showView(v){['today','patterns','timeline'].forEach(x=>{(x==='today'?$('todayView'):$(x+'View')).classList.toggle('hide',x!==v);$('n'+x[0].toUpperCase()+x.slice(1)).classList.toggle('active',x===v)});if(v==='patterns')loadPatterns();if(v==='timeline')loadTimeline()}
async function load(){const d=await get('/api/v1/today');const keys=[['sleep_duration','SLEEP',v=>v+'h'],['energy','ENERGY',v=>v+'/10'],['mood','MOOD',v=>v+'/10'],['stress','STRESS',v=>v+'/10'],['focus','FOCUS',v=>v+'/10'],['diet_quality','EATING',v=>v]];let html='';keys.forEach(x=>{if(d[x[0]]!==undefined)html+=`<div class="metric"><span>${x[1]}</span><b>${x[2](d[x[0]])}</b></div>`});$('snapshot').innerHTML=html||'<div class="empty"><b>A quiet page.</b><span>Two tiny check-ins begin the picture.</span></div>';const c=(d.sleep_duration!==undefined?1:0)+(d.mood!==undefined?1:0);$('count').textContent=`${c} / 2 check-ins`;$('bar').style.width=c*50+'%';const ins=await get('/api/v1/insights');$('insight').textContent=ins.items?.[0]||'Your baseline is beginning to take shape.';$('account').textContent='SIGN OUT'}
async function loadPatterns(){const d=await get('/api/v1/patterns');const labels=[['sleep_duration','Sleep','h'],['sleep_quality','Sleep quality','/10'],['energy','Energy','/10'],['stress','Stress','/10'],['focus','Focus','/10']];$('patternCards').innerHTML=labels.map(([k,l,u])=>d.averages?.[k]!==undefined?`<div class="pcard"><span>${l}</span><b>${d.averages[k]}${u}</b></div>`:'').join('')||'<div class="empty"><b>Still gathering signal.</b><span>Keep checking in and the pattern view will wake up.</span></div>';const series=d.series||[];$('chart').innerHTML=series.slice(-14).map(p=>{const sleep=((p.sleep_duration||0)/10)*100,focus=((p.focus||0)/10)*100;return `<div class="bar" style="height:${Math.max(sleep,focus,4)}%" title="${p.date}"></div>`}).join('')||''}
async function loadTimeline(){const rows=await get('/api/v1/timeline');$('timeline').innerHTML=rows.slice(0,60).map(r=>`<div class="event"><span>${new Date(r.recorded_at).toLocaleDateString()}</span><b>${r.kind.replaceAll('_',' ')}</b><em>${r.value}</em></div>`).join('')||'<div class="empty"><b>No observations yet.</b><span>Your first check-in will appear here.</span></div>'}
async function boot(){const d=new Date();$('date').textContent=d.toLocaleDateString(undefined,{day:'2-digit',month:'short'}).toUpperCase();$('greeting').textContent=d.getHours()<12?'Good morning.':d.getHours()<18?'Good afternoon.':'Good evening.';if(document.cookie.includes('nexgene_csrf=')){await fetch(API+'/api/v1/auth/csrf');csrf=document.cookie.split('; ').find(x=>x.startsWith('nexgene_csrf='))?.split('=')[1]||'';$('account').textContent='SIGN OUT';const me=await get('/api/v1/auth/me');if(me.id)await load();else csrf=''}}boot();
